name: 'Last Successful Commit Hash'
description:
  'Get the commit hash of the last successful run for the given workflow and
  branch'
author: 'Tyler Milner'
inputs:
  github-token:
    description: 'The GitHub token. Defaults to `${{ github.token }}`'
    required: true
    default: ${{ github.token }}
  workflow-id:
    description:
      'The workflow id or workflow file name to use for determining the last
      successful run'
    required: true
  branch:
    description: 'The branch to use for determining the last successful run'
    required: true
  debug:
    description: 'Whether or not the action should log debug information'
    required: false
    default: false
outputs:
  commit-hash:
    description: 'The commit hash for the last successful workflow run'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'git-commit'
  color: 'blue'
